language: ruby

cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

build: skip

install: skip

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
