language: ruby

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

#try skipping rake. Don't know what rake does
#script: skip
#skipping rake failed.

#trying script: jekyll build
#before_script:jekyll clean
script: jekyll build

#dpl v2(modified)
#use dpl v1(with no assigned provider)(which could be understand as 'standard','files' or ... 'github')
deploy:
  provider: pages
  cleanup: false
  github_token: "$GITHUB_TOKEN"  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
