language: ruby

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

deploy:
  provider: pages
  cleanup: false
  github_token: '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'  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
